image: listx/texlive:2016

build:Thesis:
  variables:
    LATEX_PARAMS: |
        -file-line-error -interaction=nonstopmode
  script:
    - cd Thesis
    - latexmk -pdf -pdflatex="pdflatex $LATEX_PARAMS" main
  artifacts:
    paths:
      - Thesis/main.pdf
