image: listx/texlive:2016

build:Thesis:
  variables:
    LATEX_PARAMS: |
        -file-line-error  --synctex=1 -interaction=nonstopmode "\input"
  script:
    - cd Thesis
    - pdflatex $LATEX_PARAMS main
    - bibtex Thesis/main
    - pdflatex $LATEX_PARAMS main
    - pdflatex $LATEX_PARAMS main
